services:
  # App 1: The Local Telegram Bot API Server (Running on Port 8081)
  telegram-api-server:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
    restart: always

  # App 2: Redis Database Container (Running on Port 6379)
  redis-server:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379" # This binds it ONLY to the remote server's local loopback
    restart: always
    volumes:
      - redis_data:/data

  # App 3: Node.js Bot Script (Running on Port 3000)
  video-downloader-bot:
    build: .
    image: video-downloader-bot:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "${NODE_ENV}"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_USERNAME: "${BOT_USERNAME}"
      PORT: "3000"
      REDIS_URL: "redis://redis-server:6379"
      YTDLP_COOKIES: "${YTDLP_COOKIES}"
      CHANNEL_ID: "${CHANNEL_ID}"
      LOCAL_TELEGRAM_API_SERVER: "http://telegram-api-server:8081"
      RUNNING_IN_DOCKER: "true"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - telegram-api-server
      - redis-server

volumes:
  redis_data:
